### ISSUE TITLE
request_server_cert with cert_name=None blows up easyrsa

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/interface-tls-certificates#11]
Per the code, `cert_name` is not needed when calling `request_server_cert`:

https://github.com/juju-solutions/interface-tls-certificates/blob/master/requires.py#L244

However, easyrsa expects a string for the cert name:

https://github.com/juju-solutions/layer-easyrsa/blob/master/reactive/easyrsa.py#L254

When `None` comes in, easyrsa blows up trying to do a `data_changed('server_cert.' + name, this_cert)`:
```
unit-easyrsa-1: 09:26:58 INFO unit.easyrsa/1.juju-log client:10: Invoking reactive handler: reactive/easyrsa.py:215:create_server_cert
unit-easyrsa-1: 09:26:58 ERROR unit.easyrsa/1.juju-log client:10: Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-easyrsa-1/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-easyrsa-1/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-easyrsa-1/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-easyrsa-1/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-easyrsa-1/charm/reactive/easyrsa.py", line 227, in create_server_cert
    server_cert, server_key = create_server_certificate(cn, sans, name)
  File "/var/lib/juju/agents/unit-easyrsa-1/charm/reactive/easyrsa.py", line 269, in create_server_certificate
    changed = data_changed('server_cert.' + name, this_cert)
TypeError: Can't convert 'NoneType' object to str implicitly
```

I think we could either change the default `cert_name` here to some string, or change easyrsa to handle `name=None` better.

**Comment by johnsca** [comment]
This will be fixed in the refactor, but we should resolve it here as well for non-updated deployments.
